// Chaos spell data structures. Generated by ChaosData.java

#include "spelldata.h"
#include "magic.h"
#include "platform.h"

static const struct SPELL_DATA spell_data_0 = {
    "",
    0, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    0, // castChance
    0, // castRange
    0, // ai cast priority
    0, // 16 colour palette
    0, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_1 = {
    "Disbelieve",
    0, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    10, // castChance
    41, // castRange
    0, // ai cast priority
    0, // 16 colour palette
    cast_disbelieve, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_2 = {
    "King Cobra",
    1, // chaos rating
    4, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    1, // defence
    1, // movement
    6, // manvr
    1, // magicRes
    10, // castChance
    3, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_creature, // function pointer
    binary_king_cobra_raw_start,
    binary_king_cobra_map_start,
};

static const struct SPELL_DATA spell_data_3 = {
    "Dire Wolf",
    -1, // chaos rating
    3, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    2, // defence
    3, // movement
    7, // manvr
    2, // magicRes
    9, // castChance
    3, // castRange
    18, // ai cast priority
    1, // 16 colour palette
    cast_creature, // function pointer
    binary_dire_wolf_raw_start,
    binary_dire_wolf_map_start,
};

static const struct SPELL_DATA spell_data_4 = {
    "Goblin",
    -1, // chaos rating
    2, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    4, // defence
    1, // movement
    4, // manvr
    4, // magicRes
    9, // castChance
    3, // castRange
    18, // ai cast priority
    6, // 16 colour palette
    cast_creature, // function pointer
    binary_goblin_raw_start,
    binary_goblin_map_start,
};

static const struct SPELL_DATA spell_data_5 = {
    "Crocodile",
    0, // chaos rating
    5, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    6, // defence
    1, // movement
    2, // manvr
    2, // magicRes
    8, // castChance
    3, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_creature, // function pointer
    binary_crocodile_raw_start,
    binary_crocodile_map_start,
};

static const struct SPELL_DATA spell_data_6 = {
    "Troll",
    -1, // chaos rating
    4, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    8, // defence
    1, // movement
    1, // manvr
    4, // magicRes
    6, // castChance
    3, // castRange
    18, // ai cast priority
    1, // 16 colour palette
    cast_creature, // function pointer
    binary_troll_raw_start,
    binary_troll_map_start,
};

static const struct SPELL_DATA spell_data_7 = {
    "Faun",
    -1, // chaos rating
    3, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    2, // defence
    1, // movement
    7, // manvr
    8, // magicRes
    8, // castChance
    3, // castRange
    18, // ai cast priority
    3, // 16 colour palette
    cast_creature, // function pointer
    binary_faun_raw_start,
    binary_faun_map_start,
};

static const struct SPELL_DATA spell_data_8 = {
    "Lion",
    1, // chaos rating
    6, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    4, // defence
    4, // movement
    8, // manvr
    3, // magicRes
    6, // castChance
    3, // castRange
    18, // ai cast priority
    2, // 16 colour palette
    cast_creature, // function pointer
    binary_lion_raw_start,
    binary_lion_map_start,
};

static const struct SPELL_DATA spell_data_9 = {
    "Elf",
    2, // chaos rating
    1, // combat
    2, // rangedCombat
    6, // rangedCombatRange
    2, // defence
    1, // movement
    5, // manvr
    7, // magicRes
    7, // castChance
    3, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_creature, // function pointer
    binary_elf_raw_start,
    binary_elf_map_start,
};

static const struct SPELL_DATA spell_data_10 = {
    "Orc",
    -1, // chaos rating
    2, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    1, // defence
    1, // movement
    4, // manvr
    4, // magicRes
    10, // castChance
    3, // castRange
    18, // ai cast priority
    3, // 16 colour palette
    cast_creature, // function pointer
    binary_orc_raw_start,
    binary_orc_map_start,
};

static const struct SPELL_DATA spell_data_11 = {
    "Bear",
    1, // chaos rating
    6, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    7, // defence
    2, // movement
    6, // manvr
    2, // magicRes
    6, // castChance
    3, // castRange
    18, // ai cast priority
    3, // 16 colour palette
    cast_creature, // function pointer
    binary_bear_raw_start,
    binary_bear_map_start,
};

static const struct SPELL_DATA spell_data_12 = {
    "Gorilla",
    0, // chaos rating
    6, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    5, // defence
    1, // movement
    4, // manvr
    2, // magicRes
    7, // castChance
    3, // castRange
    18, // ai cast priority
    7, // 16 colour palette
    cast_creature, // function pointer
    binary_gorilla_raw_start,
    binary_gorilla_map_start,
};

static const struct SPELL_DATA spell_data_13 = {
    "Ogre",
    -1, // chaos rating
    4, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    7, // defence
    1, // movement
    3, // manvr
    6, // magicRes
    7, // castChance
    3, // castRange
    18, // ai cast priority
    4, // 16 colour palette
    cast_creature, // function pointer
    binary_ogre_raw_start,
    binary_ogre_map_start,
};

static const struct SPELL_DATA spell_data_14 = {
    "Hydra",
    -1, // chaos rating
    7, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    8, // defence
    1, // movement
    4, // manvr
    6, // magicRes
    5, // castChance
    3, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_creature, // function pointer
    binary_hydra_raw_start,
    binary_hydra_map_start,
};

static const struct SPELL_DATA spell_data_15 = {
    "Giant Rat",
    0, // chaos rating
    1, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    1, // defence
    3, // movement
    8, // manvr
    2, // magicRes
    10, // castChance
    3, // castRange
    18, // ai cast priority
    1, // 16 colour palette
    cast_creature, // function pointer
    binary_giant_rat_raw_start,
    binary_giant_rat_map_start,
};

static const struct SPELL_DATA spell_data_16 = {
    "Giant",
    1, // chaos rating
    9, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    7, // defence
    2, // movement
    6, // manvr
    5, // magicRes
    4, // castChance
    3, // castRange
    18, // ai cast priority
    6, // 16 colour palette
    cast_creature, // function pointer
    binary_giant_raw_start,
    binary_giant_map_start,
};

static const struct SPELL_DATA spell_data_17 = {
    "Horse",
    1, // chaos rating
    1, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    3, // defence
    4, // movement
    8, // manvr
    1, // magicRes
    9, // castChance
    3, // castRange
    18, // ai cast priority
    3, // 16 colour palette
    cast_creature, // function pointer
    binary_horse_raw_start,
    binary_horse_map_start,
};

static const struct SPELL_DATA spell_data_18 = {
    "Unicorn",
    2, // chaos rating
    5, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    4, // defence
    4, // movement
    9, // manvr
    7, // magicRes
    6, // castChance
    3, // castRange
    18, // ai cast priority
    7, // 16 colour palette
    cast_creature, // function pointer
    binary_unicorn_raw_start,
    binary_unicorn_map_start,
};

static const struct SPELL_DATA spell_data_19 = {
    "Centaur",
    1, // chaos rating
    1, // combat
    2, // rangedCombat
    4, // rangedCombatRange
    3, // defence
    4, // movement
    5, // manvr
    5, // magicRes
    7, // castChance
    3, // castRange
    18, // ai cast priority
    3, // 16 colour palette
    cast_creature, // function pointer
    binary_centaur_raw_start,
    binary_centaur_map_start,
};

static const struct SPELL_DATA spell_data_20 = {
    "Pegasus",
    2, // chaos rating
    2, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    4, // defence
    5, // movement
    6, // manvr
    7, // magicRes
    7, // castChance
    3, // castRange
    18, // ai cast priority
    1, // 16 colour palette
    cast_creature, // function pointer
    binary_pegasus_raw_start,
    binary_pegasus_map_start,
};

static const struct SPELL_DATA spell_data_21 = {
    "Gryphon",
    1, // chaos rating
    3, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    5, // defence
    5, // movement
    5, // manvr
    6, // magicRes
    6, // castChance
    3, // castRange
    18, // ai cast priority
    1, // 16 colour palette
    cast_creature, // function pointer
    binary_gryphon_raw_start,
    binary_gryphon_map_start,
};

static const struct SPELL_DATA spell_data_22 = {
    "Manticore",
    -1, // chaos rating
    3, // combat
    1, // rangedCombat
    3, // rangedCombatRange
    6, // defence
    5, // movement
    6, // manvr
    8, // magicRes
    4, // castChance
    3, // castRange
    18, // ai cast priority
    2, // 16 colour palette
    cast_creature, // function pointer
    binary_manticore_raw_start,
    binary_manticore_map_start,
};

static const struct SPELL_DATA spell_data_23 = {
    "Bat",
    -1, // chaos rating
    1, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    1, // defence
    5, // movement
    9, // manvr
    4, // magicRes
    8, // castChance
    3, // castRange
    18, // ai cast priority
    1, // 16 colour palette
    cast_creature, // function pointer
    binary_bat_raw_start,
    binary_bat_map_start,
};

static const struct SPELL_DATA spell_data_24 = {
    "Green Dragon",
    -1, // chaos rating
    5, // combat
    4, // rangedCombat
    6, // rangedCombatRange
    8, // defence
    3, // movement
    4, // manvr
    4, // magicRes
    2, // castChance
    3, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_creature, // function pointer
    binary_dragon_green_raw_start,
    binary_dragon_green_map_start,
};

static const struct SPELL_DATA spell_data_25 = {
    "Red Dragon",
    -2, // chaos rating
    7, // combat
    3, // rangedCombat
    5, // rangedCombatRange
    9, // defence
    3, // movement
    4, // manvr
    5, // magicRes
    1, // castChance
    3, // castRange
    18, // ai cast priority
    4, // 16 colour palette
    cast_creature, // function pointer
    binary_dragon_red_raw_start,
    binary_dragon_red_map_start,
};

static const struct SPELL_DATA spell_data_26 = {
    "Golden Dragon",
    2, // chaos rating
    9, // combat
    5, // rangedCombat
    4, // rangedCombatRange
    9, // defence
    3, // movement
    5, // manvr
    5, // magicRes
    2, // castChance
    3, // castRange
    18, // ai cast priority
    2, // 16 colour palette
    cast_creature, // function pointer
    binary_dragon_golden_raw_start,
    binary_dragon_golden_map_start,
};

static const struct SPELL_DATA spell_data_27 = {
    "Harpy",
    -1, // chaos rating
    4, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    2, // defence
    5, // movement
    8, // manvr
    5, // magicRes
    7, // castChance
    3, // castRange
    18, // ai cast priority
    1, // 16 colour palette
    cast_creature, // function pointer
    binary_harpy_raw_start,
    binary_harpy_map_start,
};

static const struct SPELL_DATA spell_data_28 = {
    "Eagle",
    1, // chaos rating
    3, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    3, // defence
    6, // movement
    8, // manvr
    2, // magicRes
    7, // castChance
    3, // castRange
    18, // ai cast priority
    2, // 16 colour palette
    cast_creature, // function pointer
    binary_eagle_raw_start,
    binary_eagle_map_start,
};

static const struct SPELL_DATA spell_data_29 = {
    "Vampire",
    -2, // chaos rating
    6, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    8, // defence
    4, // movement
    6, // manvr
    5, // magicRes
    2, // castChance
    3, // castRange
    18, // ai cast priority
    1, // 16 colour palette
    cast_creature, // function pointer
    binary_vampire_raw_start,
    binary_vampire_map_start,
};

static const struct SPELL_DATA spell_data_30 = {
    "Ghost",
    -1, // chaos rating
    1, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    3, // defence
    2, // movement
    9, // manvr
    6, // magicRes
    5, // castChance
    3, // castRange
    18, // ai cast priority
    4, // 16 colour palette
    cast_creature, // function pointer
    binary_ghost_raw_start,
    binary_ghost_map_start,
};

static const struct SPELL_DATA spell_data_31 = {
    "Spectre",
    -1, // chaos rating
    4, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    2, // defence
    1, // movement
    6, // manvr
    4, // magicRes
    6, // castChance
    3, // castRange
    18, // ai cast priority
    7, // 16 colour palette
    cast_creature, // function pointer
    binary_spectre_raw_start,
    binary_spectre_map_start,
};

static const struct SPELL_DATA spell_data_32 = {
    "Wraith",
    -1, // chaos rating
    5, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    5, // defence
    2, // movement
    4, // manvr
    5, // magicRes
    6, // castChance
    3, // castRange
    18, // ai cast priority
    5, // 16 colour palette
    cast_creature, // function pointer
    binary_wraith_raw_start,
    binary_wraith_map_start,
};

static const struct SPELL_DATA spell_data_33 = {
    "Skeleton",
    -1, // chaos rating
    3, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    2, // defence
    1, // movement
    3, // manvr
    4, // magicRes
    7, // castChance
    3, // castRange
    18, // ai cast priority
    4, // 16 colour palette
    cast_creature, // function pointer
    binary_skeleton_raw_start,
    binary_skeleton_map_start,
};

static const struct SPELL_DATA spell_data_34 = {
    "Zombie",
    -1, // chaos rating
    1, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    1, // defence
    1, // movement
    2, // manvr
    3, // magicRes
    9, // castChance
    3, // castRange
    18, // ai cast priority
    7, // 16 colour palette
    cast_creature, // function pointer
    binary_zombie_raw_start,
    binary_zombie_map_start,
};

static const struct SPELL_DATA spell_data_35 = {
    "Gooey Blob",
    -1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    9, // castChance
    13, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_fire_goo, // function pointer
    binary_gooey_blob_raw_start,
    binary_gooey_blob_map_start,
};

static const struct SPELL_DATA spell_data_36 = {
    "Magic Fire",
    -1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    8, // castChance
    13, // castRange
    18, // ai cast priority
    4, // 16 colour palette
    cast_fire_goo, // function pointer
    binary_magic_fire_raw_start,
    binary_magic_fire_map_start,
};

static const struct SPELL_DATA spell_data_37 = {
    "Magic Wood",
    1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    8, // castChance
    17, // castRange
    17, // ai cast priority
    8, // 16 colour palette
    cast_trees_castles, // function pointer
    binary_magic_wood_raw_start,
    binary_magic_wood_map_start,
};

static const struct SPELL_DATA spell_data_38 = {
    "Shadow Wood",
    -1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    4, // castChance
    17, // castRange
    18, // ai cast priority
    5, // 16 colour palette
    cast_trees_castles, // function pointer
    binary_shadow_wood_raw_start,
    binary_shadow_wood_map_start,
};

static const struct SPELL_DATA spell_data_39 = {
    "Magic Castle",
    1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    6, // castChance
    17, // castRange
    23, // ai cast priority
    5, // 16 colour palette
    cast_trees_castles, // function pointer
    binary_magic_castle_raw_start,
    binary_magic_castle_map_start,
};

static const struct SPELL_DATA spell_data_40 = {
    "Dark Citadel",
    -1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    6, // castChance
    17, // castRange
    23, // ai cast priority
    5, // 16 colour palette
    cast_trees_castles, // function pointer
    binary_dark_citadel_raw_start,
    binary_dark_citadel_map_start,
};

static const struct SPELL_DATA spell_data_41 = {
    "Wall",
    0, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    8, // castChance
    13, // castRange
    12, // ai cast priority
    3, // 16 colour palette
    cast_wall, // function pointer
    binary_wall_raw_start,
    binary_wall_map_start,
};

static const struct SPELL_DATA spell_data_42 = {
    "Magic Bolt",
    0, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    10, // castChance
    13, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_magic_missile, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_43 = {
    "Lightning",
    0, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    10, // castChance
    9, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_magic_missile, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_44 = {
    "Vengeance",
    -1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    8, // castChance
    41, // castRange
    12, // ai cast priority
    0, // 16 colour palette
    cast_justice, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_45 = {
    "Decree",
    1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    8, // castChance
    41, // castRange
    12, // ai cast priority
    0, // 16 colour palette
    cast_justice, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_46 = {
    "Dark Power",
    -2, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    5, // castChance
    41, // castRange
    11, // ai cast priority
    0, // 16 colour palette
    cast_justice, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_47 = {
    "Justice",
    2, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    5, // castChance
    41, // castRange
    11, // ai cast priority
    0, // 16 colour palette
    cast_justice, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_48 = {
    "Magic Shield",
    1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    7, // castChance
    0, // castRange
    23, // ai cast priority
    0, // 16 colour palette
    cast_magic_shield, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_49 = {
    "Magic Armour",
    1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    4, // castChance
    0, // castRange
    23, // ai cast priority
    0, // 16 colour palette
    cast_magic_armour, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_50 = {
    "Magic Sword",
    1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    4, // castChance
    0, // castRange
    16, // ai cast priority
    0, // 16 colour palette
    cast_magic_sword, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_51 = {
    "Magic Knife",
    1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    7, // castChance
    0, // castRange
    16, // ai cast priority
    0, // 16 colour palette
    cast_magic_knife, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_52 = {
    "Magic Bow",
    1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    5, // castChance
    0, // castRange
    17, // ai cast priority
    0, // 16 colour palette
    cast_magic_bow, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_53 = {
    "Magic Wings",
    0, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    5, // castChance
    0, // castRange
    14, // ai cast priority
    0, // 16 colour palette
    cast_magic_wings, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_54 = {
    "Law 1",
    2, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    8, // castChance
    0, // castRange
    5, // ai cast priority
    0, // 16 colour palette
    cast_chaos_law, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_55 = {
    "Law 2",
    4, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    6, // castChance
    0, // castRange
    6, // ai cast priority
    0, // 16 colour palette
    cast_chaos_law, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_56 = {
    "Chaos 1",
    -2, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    8, // castChance
    0, // castRange
    5, // ai cast priority
    0, // 16 colour palette
    cast_chaos_law, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_57 = {
    "Chaos 2",
    -4, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    6, // castChance
    0, // castRange
    6, // ai cast priority
    0, // 16 colour palette
    cast_chaos_law, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_58 = {
    "Shadow Form",
    0, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    8, // castChance
    0, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_shadow_form, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_59 = {
    "Subversion",
    0, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    10, // castChance
    15, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_subversion, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_60 = {
    "Raise Dead",
    -1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    5, // castChance
    9, // castRange
    18, // ai cast priority
    0, // 16 colour palette
    cast_raise_dead, // function pointer
    0,
    0,
};

static const struct SPELL_DATA spell_data_61 = {
    "Turmoil",
    -1, // chaos rating
    0, // combat
    0, // rangedCombat
    0, // rangedCombatRange
    0, // defence
    0, // movement
    0, // manvr
    0, // magicRes
    5, // castChance
    0, // castRange
    17, // ai cast priority
    0, // 16 colour palette
    cast_turmoil, // function pointer
    0,
    0,
};


static const struct SPELL_DATA* const spell_table[] = {
    &spell_data_0,
    &spell_data_1,
    &spell_data_2,
    &spell_data_3,
    &spell_data_4,
    &spell_data_5,
    &spell_data_6,
    &spell_data_7,
    &spell_data_8,
    &spell_data_9,
    &spell_data_10,
    &spell_data_11,
    &spell_data_12,
    &spell_data_13,
    &spell_data_14,
    &spell_data_15,
    &spell_data_16,
    &spell_data_17,
    &spell_data_18,
    &spell_data_19,
    &spell_data_20,
    &spell_data_21,
    &spell_data_22,
    &spell_data_23,
    &spell_data_24,
    &spell_data_25,
    &spell_data_26,
    &spell_data_27,
    &spell_data_28,
    &spell_data_29,
    &spell_data_30,
    &spell_data_31,
    &spell_data_32,
    &spell_data_33,
    &spell_data_34,
    &spell_data_35,
    &spell_data_36,
    &spell_data_37,
    &spell_data_38,
    &spell_data_39,
    &spell_data_40,
    &spell_data_41,
    &spell_data_42,
    &spell_data_43,
    &spell_data_44,
    &spell_data_45,
    &spell_data_46,
    &spell_data_47,
    &spell_data_48,
    &spell_data_49,
    &spell_data_50,
    &spell_data_51,
    &spell_data_52,
    &spell_data_53,
    &spell_data_54,
    &spell_data_55,
    &spell_data_56,
    &spell_data_57,
    &spell_data_58,
    &spell_data_59,
    &spell_data_60,
    &spell_data_61,
};
const struct SPELL_DATA_ALL CHAOS_SPELLS = {
    62, // number of spells
    spell_table, // pointer to spells
};
