// Chaos spell data structures. Generated by ChaosData.java

#define SPELL_DISBELIEVE 1
#define SPELL_KING_COBRA 2
#define SPELL_DIRE_WOLF 3
#define SPELL_GOBLIN 4
#define SPELL_CROCODILE 5
#define SPELL_TROLL 6
#define SPELL_FAUN 7
#define SPELL_LION 8
#define SPELL_ELF 9
#define SPELL_ORC 10
#define SPELL_BEAR 11
#define SPELL_GORILLA 12
#define SPELL_OGRE 13
#define SPELL_HYDRA 14
#define SPELL_GIANT_RAT 15
#define SPELL_GIANT 16
#define SPELL_HORSE 17
#define SPELL_UNICORN 18
#define SPELL_CENTAUR 19
#define SPELL_PEGASUS 20
#define SPELL_GRYPHON 21
#define SPELL_MANTICORE 22
#define SPELL_BAT 23
#define SPELL_DRAGON_GREEN 24
#define SPELL_DRAGON_RED 25
#define SPELL_DRAGON_GOLDEN 26
#define SPELL_HARPY 27
#define SPELL_EAGLE 28
#define SPELL_VAMPIRE 29
#define SPELL_GHOST 30
#define SPELL_SPECTRE 31
#define SPELL_WRAITH 32
#define SPELL_SKELETON 33
#define SPELL_ZOMBIE 34
#define SPELL_GOOEY_BLOB 35
#define SPELL_MAGIC_FIRE 36
#define SPELL_MAGIC_WOOD 37
#define SPELL_SHADOW_WOOD 38
#define SPELL_MAGIC_CASTLE 39
#define SPELL_DARK_CITADEL 40
#define SPELL_WALL 41
#define SPELL_MAGIC_BOLT 42
#define SPELL_LIGHTNING 43
#define SPELL_VENGEANCE 44
#define SPELL_DECREE 45
#define SPELL_DARK_POWER 46
#define SPELL_JUSTICE 47
#define SPELL_MAGIC_SHIELD 48
#define SPELL_MAGIC_ARMOUR 49
#define SPELL_MAGIC_SWORD 50
#define SPELL_MAGIC_KNIFE 51
#define SPELL_MAGIC_BOW 52
#define SPELL_MAGIC_WINGS 53
#define SPELL_LAW_1 54
#define SPELL_LAW_2 55
#define SPELL_CHAOS_1 56
#define SPELL_CHAOS_2 57
#define SPELL_SHADOW_FORM 58
#define SPELL_SUBVERSION 59
#define SPELL_RAISE_DEAD 60
#define SPELL_TURMOIL 61


#if !defined (__MINGW32__)
#define     binary_king_cobra_raw_start  _binary_king_cobra_raw_start
#define     binary_king_cobra_map_start  _binary_king_cobra_map_start
#endif
extern unsigned char binary_king_cobra_raw_start[];
extern unsigned char binary_king_cobra_map_start[];
#if !defined (__MINGW32__)
#define     binary_dire_wolf_raw_start  _binary_dire_wolf_raw_start
#define     binary_dire_wolf_map_start  _binary_dire_wolf_map_start
#endif
extern unsigned char binary_dire_wolf_raw_start[];
extern unsigned char binary_dire_wolf_map_start[];
#if !defined (__MINGW32__)
#define     binary_goblin_raw_start  _binary_goblin_raw_start
#define     binary_goblin_map_start  _binary_goblin_map_start
#endif
extern unsigned char binary_goblin_raw_start[];
extern unsigned char binary_goblin_map_start[];
#if !defined (__MINGW32__)
#define     binary_crocodile_raw_start  _binary_crocodile_raw_start
#define     binary_crocodile_map_start  _binary_crocodile_map_start
#endif
extern unsigned char binary_crocodile_raw_start[];
extern unsigned char binary_crocodile_map_start[];
#if !defined (__MINGW32__)
#define     binary_troll_raw_start  _binary_troll_raw_start
#define     binary_troll_map_start  _binary_troll_map_start
#endif
extern unsigned char binary_troll_raw_start[];
extern unsigned char binary_troll_map_start[];
#if !defined (__MINGW32__)
#define     binary_faun_raw_start  _binary_faun_raw_start
#define     binary_faun_map_start  _binary_faun_map_start
#endif
extern unsigned char binary_faun_raw_start[];
extern unsigned char binary_faun_map_start[];
#if !defined (__MINGW32__)
#define     binary_lion_raw_start  _binary_lion_raw_start
#define     binary_lion_map_start  _binary_lion_map_start
#endif
extern unsigned char binary_lion_raw_start[];
extern unsigned char binary_lion_map_start[];
#if !defined (__MINGW32__)
#define     binary_elf_raw_start  _binary_elf_raw_start
#define     binary_elf_map_start  _binary_elf_map_start
#endif
extern unsigned char binary_elf_raw_start[];
extern unsigned char binary_elf_map_start[];
#if !defined (__MINGW32__)
#define     binary_orc_raw_start  _binary_orc_raw_start
#define     binary_orc_map_start  _binary_orc_map_start
#endif
extern unsigned char binary_orc_raw_start[];
extern unsigned char binary_orc_map_start[];
#if !defined (__MINGW32__)
#define     binary_bear_raw_start  _binary_bear_raw_start
#define     binary_bear_map_start  _binary_bear_map_start
#endif
extern unsigned char binary_bear_raw_start[];
extern unsigned char binary_bear_map_start[];
#if !defined (__MINGW32__)
#define     binary_gorilla_raw_start  _binary_gorilla_raw_start
#define     binary_gorilla_map_start  _binary_gorilla_map_start
#endif
extern unsigned char binary_gorilla_raw_start[];
extern unsigned char binary_gorilla_map_start[];
#if !defined (__MINGW32__)
#define     binary_ogre_raw_start  _binary_ogre_raw_start
#define     binary_ogre_map_start  _binary_ogre_map_start
#endif
extern unsigned char binary_ogre_raw_start[];
extern unsigned char binary_ogre_map_start[];
#if !defined (__MINGW32__)
#define     binary_hydra_raw_start  _binary_hydra_raw_start
#define     binary_hydra_map_start  _binary_hydra_map_start
#endif
extern unsigned char binary_hydra_raw_start[];
extern unsigned char binary_hydra_map_start[];
#if !defined (__MINGW32__)
#define     binary_giant_rat_raw_start  _binary_giant_rat_raw_start
#define     binary_giant_rat_map_start  _binary_giant_rat_map_start
#endif
extern unsigned char binary_giant_rat_raw_start[];
extern unsigned char binary_giant_rat_map_start[];
#if !defined (__MINGW32__)
#define     binary_giant_raw_start  _binary_giant_raw_start
#define     binary_giant_map_start  _binary_giant_map_start
#endif
extern unsigned char binary_giant_raw_start[];
extern unsigned char binary_giant_map_start[];
#if !defined (__MINGW32__)
#define     binary_horse_raw_start  _binary_horse_raw_start
#define     binary_horse_map_start  _binary_horse_map_start
#endif
extern unsigned char binary_horse_raw_start[];
extern unsigned char binary_horse_map_start[];
#if !defined (__MINGW32__)
#define     binary_unicorn_raw_start  _binary_unicorn_raw_start
#define     binary_unicorn_map_start  _binary_unicorn_map_start
#endif
extern unsigned char binary_unicorn_raw_start[];
extern unsigned char binary_unicorn_map_start[];
#if !defined (__MINGW32__)
#define     binary_centaur_raw_start  _binary_centaur_raw_start
#define     binary_centaur_map_start  _binary_centaur_map_start
#endif
extern unsigned char binary_centaur_raw_start[];
extern unsigned char binary_centaur_map_start[];
#if !defined (__MINGW32__)
#define     binary_pegasus_raw_start  _binary_pegasus_raw_start
#define     binary_pegasus_map_start  _binary_pegasus_map_start
#endif
extern unsigned char binary_pegasus_raw_start[];
extern unsigned char binary_pegasus_map_start[];
#if !defined (__MINGW32__)
#define     binary_gryphon_raw_start  _binary_gryphon_raw_start
#define     binary_gryphon_map_start  _binary_gryphon_map_start
#endif
extern unsigned char binary_gryphon_raw_start[];
extern unsigned char binary_gryphon_map_start[];
#if !defined (__MINGW32__)
#define     binary_manticore_raw_start  _binary_manticore_raw_start
#define     binary_manticore_map_start  _binary_manticore_map_start
#endif
extern unsigned char binary_manticore_raw_start[];
extern unsigned char binary_manticore_map_start[];
#if !defined (__MINGW32__)
#define     binary_bat_raw_start  _binary_bat_raw_start
#define     binary_bat_map_start  _binary_bat_map_start
#endif
extern unsigned char binary_bat_raw_start[];
extern unsigned char binary_bat_map_start[];
#if !defined (__MINGW32__)
#define     binary_dragon_green_raw_start  _binary_dragon_green_raw_start
#define     binary_dragon_green_map_start  _binary_dragon_green_map_start
#endif
extern unsigned char binary_dragon_green_raw_start[];
extern unsigned char binary_dragon_green_map_start[];
#if !defined (__MINGW32__)
#define     binary_dragon_red_raw_start  _binary_dragon_red_raw_start
#define     binary_dragon_red_map_start  _binary_dragon_red_map_start
#endif
extern unsigned char binary_dragon_red_raw_start[];
extern unsigned char binary_dragon_red_map_start[];
#if !defined (__MINGW32__)
#define     binary_dragon_golden_raw_start  _binary_dragon_golden_raw_start
#define     binary_dragon_golden_map_start  _binary_dragon_golden_map_start
#endif
extern unsigned char binary_dragon_golden_raw_start[];
extern unsigned char binary_dragon_golden_map_start[];
#if !defined (__MINGW32__)
#define     binary_harpy_raw_start  _binary_harpy_raw_start
#define     binary_harpy_map_start  _binary_harpy_map_start
#endif
extern unsigned char binary_harpy_raw_start[];
extern unsigned char binary_harpy_map_start[];
#if !defined (__MINGW32__)
#define     binary_eagle_raw_start  _binary_eagle_raw_start
#define     binary_eagle_map_start  _binary_eagle_map_start
#endif
extern unsigned char binary_eagle_raw_start[];
extern unsigned char binary_eagle_map_start[];
#if !defined (__MINGW32__)
#define     binary_vampire_raw_start  _binary_vampire_raw_start
#define     binary_vampire_map_start  _binary_vampire_map_start
#endif
extern unsigned char binary_vampire_raw_start[];
extern unsigned char binary_vampire_map_start[];
#if !defined (__MINGW32__)
#define     binary_ghost_raw_start  _binary_ghost_raw_start
#define     binary_ghost_map_start  _binary_ghost_map_start
#endif
extern unsigned char binary_ghost_raw_start[];
extern unsigned char binary_ghost_map_start[];
#if !defined (__MINGW32__)
#define     binary_spectre_raw_start  _binary_spectre_raw_start
#define     binary_spectre_map_start  _binary_spectre_map_start
#endif
extern unsigned char binary_spectre_raw_start[];
extern unsigned char binary_spectre_map_start[];
#if !defined (__MINGW32__)
#define     binary_wraith_raw_start  _binary_wraith_raw_start
#define     binary_wraith_map_start  _binary_wraith_map_start
#endif
extern unsigned char binary_wraith_raw_start[];
extern unsigned char binary_wraith_map_start[];
#if !defined (__MINGW32__)
#define     binary_skeleton_raw_start  _binary_skeleton_raw_start
#define     binary_skeleton_map_start  _binary_skeleton_map_start
#endif
extern unsigned char binary_skeleton_raw_start[];
extern unsigned char binary_skeleton_map_start[];
#if !defined (__MINGW32__)
#define     binary_zombie_raw_start  _binary_zombie_raw_start
#define     binary_zombie_map_start  _binary_zombie_map_start
#endif
extern unsigned char binary_zombie_raw_start[];
extern unsigned char binary_zombie_map_start[];
#if !defined (__MINGW32__)
#define     binary_gooey_blob_raw_start  _binary_gooey_blob_raw_start
#define     binary_gooey_blob_map_start  _binary_gooey_blob_map_start
#endif
extern unsigned char binary_gooey_blob_raw_start[];
extern unsigned char binary_gooey_blob_map_start[];
#if !defined (__MINGW32__)
#define     binary_magic_fire_raw_start  _binary_magic_fire_raw_start
#define     binary_magic_fire_map_start  _binary_magic_fire_map_start
#endif
extern unsigned char binary_magic_fire_raw_start[];
extern unsigned char binary_magic_fire_map_start[];
#if !defined (__MINGW32__)
#define     binary_magic_wood_raw_start  _binary_magic_wood_raw_start
#define     binary_magic_wood_map_start  _binary_magic_wood_map_start
#endif
extern unsigned char binary_magic_wood_raw_start[];
extern unsigned char binary_magic_wood_map_start[];
#if !defined (__MINGW32__)
#define     binary_shadow_wood_raw_start  _binary_shadow_wood_raw_start
#define     binary_shadow_wood_map_start  _binary_shadow_wood_map_start
#endif
extern unsigned char binary_shadow_wood_raw_start[];
extern unsigned char binary_shadow_wood_map_start[];
#if !defined (__MINGW32__)
#define     binary_magic_castle_raw_start  _binary_magic_castle_raw_start
#define     binary_magic_castle_map_start  _binary_magic_castle_map_start
#endif
extern unsigned char binary_magic_castle_raw_start[];
extern unsigned char binary_magic_castle_map_start[];
#if !defined (__MINGW32__)
#define     binary_dark_citadel_raw_start  _binary_dark_citadel_raw_start
#define     binary_dark_citadel_map_start  _binary_dark_citadel_map_start
#endif
extern unsigned char binary_dark_citadel_raw_start[];
extern unsigned char binary_dark_citadel_map_start[];
#if !defined (__MINGW32__)
#define     binary_wall_raw_start  _binary_wall_raw_start
#define     binary_wall_map_start  _binary_wall_map_start
#endif
extern unsigned char binary_wall_raw_start[];
extern unsigned char binary_wall_map_start[];
struct SPELL_DATA
{
   const char* spellName;
   const signed char chaosRating;
   const unsigned char combat;
   const unsigned char rangedCombat;
   const unsigned char rangedCombatRange;
   const unsigned char defence;
   const unsigned char movement;
   const unsigned char manvr;
   const unsigned char magicRes;
   const unsigned char castChance;
   const unsigned char castRange;
   const unsigned char castPriority;
   const unsigned char palette;
   void (*pFunc)(void); // pointer to the spell casting function
   const unsigned char *pGFX;  // pointer to the graphics array (extern u8 _binary_GFX_raw_start[];)
   const unsigned char *pGFXMap; // pointer to the map file that makes up the graphics (extern u8 _binary_GFX_map_start[];)
};
struct SPELL_DATA_ALL 
{
  const unsigned char nSpellCount; // number of spells
  const struct SPELL_DATA *const *pSpellDataTable;
};
extern const struct SPELL_DATA_ALL CHAOS_SPELLS;
